version: "3.8"

services:
  message-sender:
    image: ghcr.io/its-kaktos/telegrambots-message-sender:add-youtube-bot.7399166222
    restart: always
    environment:
      - Serilog__Properties__ApplicationVersion=add-youtube-bot.7396060558
      - InstagramBotConfiguration__BotToken=BOTTOKEN
      - InstagramBotConfiguration__BaseUrl=http://telegram-local:8081
      - YoutubeBotConfiguration__BotToken=BOTTOKEN
      - YoutubeBotConfiguration__BaseUrl=http://telegram-local:8081
      - ConnectionStrings__YoutubeCache=Server=mssql,1433;Database=YoutubeCache;User Id=SA;Password=PASSWORD;TrustServerCertificate=true;
      - ConnectionStrings__InstagramCache=Server=mssql,1433;Database=InstagramCache;User Id=SA;Password=PASSWORD;TrustServerCertificate=true;
      - DOTNET_ENVIRONMENT=Production
      - RabbitMqConfig__AppId=instagram69_telegram_bot
      - RabbitMqConfig__ExchangeName=telegram_message_sender_events
      - RabbitMqConfig__QueueName=telegram_message_sender_queue
      - RabbitMqConfig__RoutingKey=telegram_message_sender_key
      - RabbitMqServerConfig__ConsumerDispatchConcurrency=1
      - RabbitMqServerConfig__PrefetchCount=100
      - RabbitMqServerConfig__HostName=rabbitmq
      - RabbitMqServerConfig__UserName=kaktos
      - RabbitMqServerConfig__Password=PASSWORD
      - RabbitMqServerConfig__Port=5672
      - Serilog__WriteTo__Seq__Args__serverUrl=http://seq:5341
    volumes:
      - /home/kaktos/volumes/shared/saved-thumbnails/:/tmp/saved-thumbnails/
      - /home/kaktos/volumes/shared/cache/:/tmp/cache/
    networks:
      - base-docker-files_insta69

networks:
  base-docker-files_insta69:
    external: true
