name: Build and push youtube docker images

env:
  DOTNET_VERSION: '7.0.x'

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        required: true
        description: "Branch name"
      IMAGE_NAME:
        required: true
        description: "Image name"

jobs:
  push-youtube69bot-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.IMAGE_NAME == 'bot' || github.event.inputs.IMAGE_NAME == 'all'}}
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: './src/Youtube69bot/'
        shell: bash
    steps:
      - name: Checkout requested branch
        uses: actions/checkout@main
        with:
          ref:  ${{ env.BRANCH }}
        env:
          BRANCH: ${{ inputs.BRANCH_NAME }}

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push youtube69bot Image'
        run: |
          docker build . --tag ghcr.io/its-kaktos/youtube69bot:"$IMAGE_VERSION"
          docker push ghcr.io/its-kaktos/youtube69bot:"$IMAGE_VERSION"
        env:
          IMAGE_VERSION: ${{ inputs.BRANCH_NAME }}.${{ github.run_id }}

  push-youtube-downloader-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.IMAGE_NAME == 'downloader' || github.event.inputs.IMAGE_NAME == 'all'}}
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: './src/Youtube69bot.Downloader/'
        shell: bash
    steps:
      - name: Checkout requested branch
        uses: actions/checkout@main
        with:
          ref:  ${{ env.BRANCH }}
        env:
          BRANCH: ${{ inputs.BRANCH_NAME }}

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push youtube69bot Image'
        run: |
          docker build . --tag ghcr.io/its-kaktos/youtube69bot-downloader:"$IMAGE_VERSION"
          docker push ghcr.io/its-kaktos/youtube69bot-downloader:"$IMAGE_VERSION"
        env:
          IMAGE_VERSION: ${{ inputs.BRANCH_NAME }}.${{ github.run_id }}
